### ISSUE TITLE
Calendar view for month

### ISSUE THREAD

**Issue by MsZoezo** [MsZoezo/dayta#3]
# What is the Problem?
There is no month calendar view.

# Why is This a Problem?
Without a month calendar view, the user cannot see their schedule for the selected month in a glance.

# How do We Fix it?
We'll add a calendar view with 31 blocks for every day of the month up to 31 days.

**Comment by BetOnJeanette** [comment]
@MsZoezo I know we said that we wanted the buttons right next to the month + year, but I found that it got pretty annoying, as they would shift whenever you would change the month, so I pushed the buttons to the edge

**Comment by MsZoezo** [comment]
I was afraid that would happen, i was thinking about leaving enough space for the widest the text could be. But then with short text they float in the middle of nowhere-
